### ISSUE TITLE
GPU incorrectly recognized as RTX 3080

### ISSUE THREAD

**Issue by jomaskm** [nepnep39/neofetch-win#14]
As written in the title, the GPU is recognized as an RTX 3080.
The installed GPU is a 3090.

See attached screenshots.

Please let me know if I can be of help with debug logs or something like that.

Thank you for releasing this on Windows. :)
![image](https://github.com/nepnep39/neofetch-win/assets/30002504/f463f810-f95d-4742-9b27-7ce368757f1e)
![image](https://github.com/nepnep39/neofetch-win/assets/30002504/298218df-af4b-4c80-9c9f-0d680c81b71b)

**Comment by nepnep39** [comment]
did you ever have a 3080 in there? if so, run winsat.exe and it should update the info :)

**Comment by jomaskm** [comment]
I did have a 3080 before, yes.

It didn't update the info when running WinSat though. I'll try some more when I get home tomorrow. Thanks.

**Comment by nepnep39** [comment]
if you can't get it to work through WinSAT, out of curiosity, could you try downloading GPU-Z and taking a look at how much memory your card has? reason I ask is I've heard of cards being sold as high end cards when they are in reality not, but the firmware is modified so that the card falsely reports its model. I highly doubt that's the case but it can't hurt to check, especially if you bought your card used

**Comment by nepnep39** [comment]
its been a while so I'm going to close this, if you still need help feel free to reopen it
