### ISSUE TITLE
Config file/How to build

### ISSUE THREAD

**Issue by SenZmaKi** [nepnep39/neofetch-win#18]
Dope project, and it's also the fastest windows neofetch I've project but then comes the customisation. I don't know anything about Cpp, I've spent the past 3 hour trying to build so that I can customise the ascii art but I've just been getting compilation error after compilation error, can you add like a config file option or something cause having to build just to customise the art is a pain.

**Comment by SenZmaKi** [comment]
Nevermind I found a solution. Incase anyone else faced the same problem I found out some include statements were missing, I edited the include statements in `neofetch-win/neofetch-win/source.cpp` to

```cpp
#include <winreg.h>
﻿#include <algorithm>
#include <iostream>
#include <random>
#include <string>
#include <vector>
```
command I ran during build, ran from the root directory  `msbuild.exe /p:IncludePath=. /nologo /clp:ErrorsOnly /p:Configuration=Release`

**Comment by nepnep39** [comment]
Sorry, I was sleeping at the time lol
if you're compiling with c++17 or earlier you will need these headers:

```c++
#include <iostream>
#include <windows.h>
#include <string.h>
#include <Lmcons.h>
#include <chrono>
#include <iomanip>
#include <algorithm>

```
however, if you're compiling with c++20 those last two headers are unnessecary because iomanip.h and IIRC some of algorithm.h is now included in the standard library. To clear up any further confusion I have decided to update the source so that it will compile in older C++ versions. I will also include a compile config in the readme.
Thanks for the ticket, feel free to reopen if you have any other questions
